class ELEV_CONFIG:
    ARRIVAL_MAX = 2
    ARRIVAL_MIN = 1    
    WALKING_MAX = 3
    WALKING_MIN = 1
    RANDOM_SEED = 50
    ELEV_CAPACITY = 20
    ELEV_VELOCITY = 10
    CUSTOMER__RECALL_ELEV_TIME = ELEV_VELOCITY + 2
    ELEV_OPEN = 1
    ELEV_CLOSE = 1
    VERSION = 4