class ELEV_CONFIG:
    ARRIVAL_MAX = 2
    ARRIVAL_MIN = 1    
    WALKING_MAX = 3
    WALKING_MIN = 1
    RANDOM_SEED = 50
    ELEV_CAPACITY = 20


class ELEVLOG_CONFIG:
    IDLE = 0
    ARRIVE = 1
    SERVE = 2